### ISSUE TITLE
new UIlang.zh-CN.xaml

### ISSUE THREAD

**Issue by yoaan** [f11894/waifu2x-ncnn-vulkan-GUI#1]
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:sys="clr-namespace:System;assembly=mscorlib">
    <sys:String x:Key="ResourceDictionaryName">waifu2xui-zh-CN</sys:String>
    
    <sys:String x:Key="MainWnd_Title">waifu2x-ncnn-vulkan multilingual图形界面</sys:String>
    <sys:String x:Key="MainMenu_About">关于</sys:String>
    <sys:String x:Key="MainMenu_Help">帮助</sys:String>
    <sys:String x:Key="MainMenu_Version">版本信息</sys:String>
    
    <sys:String x:Key="MainTab_IO">输入输出设置</sys:String>
    
    <sys:String x:Key="Main_IO_SrcPath">输入路径：</sys:String>
    <sys:String x:Key="Main_IO_DstPath">输出路径：</sys:String>
    <sys:String x:Key="Main_IO_btnSrc">选择输入路径</sys:String>
    <sys:String x:Key="Main_IO_SrcClear">清除</sys:String>
    <sys:String x:Key="Main_IO_btnDst">选择输出路径</sys:String>
    <sys:String x:Key="Main_IO_DstClear">清除</sys:String>
    <sys:String x:Key="Main_IO_Src_Tooltip">输入文件名或文件夹（必须）</sys:String>
    <sys:String x:Key="Main_IO_Dst_Tooltip">输出文件名或文件夹，若留空将在输入路径下自动生成对应文件</sys:String>
    
    <sys:String x:Key="Main_Mode_Set">转换模式</sys:String>
    <sys:String x:Key="Main_Mode_Set_NoiseScale">降噪 &amp; 放大</sys:String>
    <sys:String x:Key="Main_Mode_Set_Scale">只放大</sys:String>
    <sys:String x:Key="Main_Mode_Set_Noise">只降噪</sys:String> 
    <sys:String x:Key="Main_Mode_Mag">放大倍数 （2.0~16.0）:</sys:String>
    <sys:String x:Key="Main_Mode_Denoise">降噪程度</sys:String>
    <sys:String x:Key="Main_Mode_Set_AutoScale">放大 &amp; 降噪（仅jpg）</sys:String>
    <sys:String x:Key="Main_Mode_Denoise_0">低</sys:String>
    <sys:String x:Key="Main_Mode_Denoise_1">中</sys:String>
    <sys:String x:Key="Main_Mode_Denoise_2">高</sys:String>
    <sys:String x:Key="Main_Mode_Denoise_3">最高</sys:String>
    <sys:String x:Key="Main_Mode_Model">风格</sys:String>
    <sys:String x:Key="Main_Mode_Model_CUnet">2D插图（CUnet模型）</sys:String>
    <sys:String x:Key="Main_Mode_Model_UpRGB">2D插图（UpRGB模型）</sys:String> 
    <sys:String x:Key="Main_Mode_Model_UpPhoto">照片 (UpPhoto模型)</sys:String> 
    <sys:String x:Key="Main_Device_Block">每块大小</sys:String>
    <sys:String x:Key="Main_Device_gp">设备</sys:String>
    <sys:String x:Key="Main_Device_GPU_ID">GPU ID</sys:String>
    
    <sys:String x:Key="MainTab_Preferences">偏好</sys:String>
    
    <sys:String x:Key="Main_checkStore_output_dir">存储最后的输出路径</sys:String>
    <sys:String x:Key="Main_checkOutput_no_overwirit">输出文件无覆盖</sys:String>
    <sys:String x:Key="Main_checkSoundBeep">处理后播放提示音</sys:String>
    <sys:String x:Key="Main_checkPrecision_fp32">执行高精度处理（fp32模式）</sys:String>
    <sys:String x:Key="Main_checkAlphachannel_ImageMagick">使用ImageMagick分离Alpha通道</sys:String>
    
    <sys:String x:Key="Main_btnRun">执行！</sys:String>
    
    <sys:String x:Key="Main_btnAbort">终止</sys:String>
</ResourceDictionary>

**Comment by yoaan** [comment]
<sys:String x:Key="Main_checkOutput_no_overwirit">输出文件不覆盖</sys:String>

**Comment by f11894** [comment]
Thank you for your help with the translation.
