### ISSUE TITLE
対応言語の中で韓国語がないため、韓国語ファイルを作成しました。

### ISSUE THREAD

**Issue by laikal** [f11894/waifu2x-ncnn-vulkan-GUI#10]
![K-004](https://user-images.githubusercontent.com/72580369/95515747-13e1bd80-09f9-11eb-9173-b4c200c447c5.jpg)
![K-003](https://user-images.githubusercontent.com/72580369/95515756-15ab8100-09f9-11eb-847d-73ac6f1e9b2a.jpg)

[UIlang.ko-KR.zip](https://github.com/f11894/waifu2x-ncnn-vulkan-GUI/files/5351353/UIlang.ko-KR.zip)

少しでも役に立てればと思い、韓国語の言語ファイルを作成しました。
いつも応援しています。

**Comment by f11894** [comment]
翻訳にご協力いただきありがとうございます。
