### ISSUE TITLE
White image error

### ISSUE THREAD

**Issue by theruleof4** [f11894/waifu2x-ncnn-vulkan-GUI#11]
Sometimes,  the program creates a white image, blank, different from the original image. Check the results and my configuration:

![image](https://user-images.githubusercontent.com/62116034/103441142-abd2fa00-4c2a-11eb-8f6b-db9c5e359de6.png)

![image](https://user-images.githubusercontent.com/62116034/103441148-b5f4f880-4c2a-11eb-84f1-0e7dda8f3320.png)

This happened when I dropped a folder directly to the program, in case this information is useful.

Edit 1: The source images are in png format as well

**Comment by f11894** [comment]
Can you use this executable to see if the issue has been resolved?
https://ci.appveyor.com/project/f11894/waifu2x-ncnn-vulkan-gui/builds/37073567/artifacts

**Comment by theruleof4** [comment]
> Can you use this executable to see if the issue has been resolved?
> https://ci.appveyor.com/project/f11894/waifu2x-ncnn-vulkan-gui/builds/37073567/artifacts

This worked well, converting from png to jpg. Thanks for your attention!
