### ISSUE TITLE
表記が見切れます、他要望

### ISSUE THREAD

**Issue by apapanda** [f11894/waifu2x-ncnn-vulkan-GUI#13]
台湾語表記以外だとウィンドウから設定値入力部分が見切れてしまい煩わしい。
ウィンドウサイズを可変にするか見切れないようにしてほしい。
又、出力画像の色深度設定を追加できますか？

**Comment by f11894** [comment]
レイアウトが崩れる問題はおそらく直ったかと思われます。
出力画像の色深度設定に関してはwaifu2x-ncnn-vulkanにそのような設定が無いため難しいです。

**Comment by apapanda** [comment]
修正ありがとうございます。
