### ISSUE TITLE
Contribution: Improved Brazilian Portuguese translation

### ISSUE THREAD

**Issue by flaviojcojr** [f11894/waifu2x-ncnn-vulkan-GUI#18]
I made some minor corrections to the Brazilian Portuguese translation. The file is attached.
[UILang.pt-BR.zip](https://github.com/f11894/waifu2x-ncnn-vulkan-GUI/files/7920602/UILang.pt-BR.zip)

**Comment by f11894** [comment]
Thank you as always.
