### ISSUE TITLE
Suggestion: Put Magnify Only as the first option.

### ISSUE THREAD

**Issue by flaviojcojr** [f11894/waifu2x-ncnn-vulkan-GUI#19]
Currently Magnify Only (拡大) is in the second position in the program, even though it is the default option. In several tests I performed with images, the Magnify Only option had great results, I agree that it should remain the default option.
So, I think it would be interesting for this to be the first position with Denoise&Magnify going to the second position.
![image](https://user-images.githubusercontent.com/60268722/158912280-f12f0613-67a6-4b0c-a311-28652919291f.png)

**Comment by f11894** [comment]
The order follows waifu2x-caffe.
Since waifu2x-ncnn-vulkan-GUI aims to be a waifu2x-caffe that works on AMD environment, I think it is fine as it is.

**Comment by flaviojcojr** [comment]
> The order follows waifu2x-caffe. Since waifu2x-ncnn-vulkan-GUI aims to be a waifu2x-caffe that works on AMD environment, I think it is fine as it is.

Got it now, thanks for the clarification!
