### ISSUE TITLE
TTA modeのチェックを外すとエラーとなる

### ISSUE THREAD

**Issue by apapanda** [f11894/waifu2x-ncnn-vulkan-GUI#20]
エラーログ
Error: The process failed and will be retried.
cmd.exe /C .\fp32\waifu2x-ncnn-vulkan.exe  -i "C:\Users\****\AppData\Local\Temp\8502276d685f44c3a0a46ca056580901-RGB1x.png" -o "C:\Users\****\AppData\Local\Temp\8502276d685f44c3a0a46ca056580901-RGB2x.png" -s 2 -n 2 -m models-cunet -t 512  -g 0&& .\fp32\waifu2x-ncnn-vulkan.exe  -i "C:\Users\****\AppData\Local\Temp\8502276d685f44c3a0a46ca056580901-Alpha1x.png" -o "C:\Users\****\AppData\Local\Temp\8502276d685f44c3a0a46ca056580901-Alpha2x.png" -s 2 -n -1 -m models-cunet -t 512  -g 0
[0 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

4回程エラーが出た後動作停止。

AMD Ryzen 7 5700G with Radeon Graphics
APU - AMD Radeon(TM) Graphics - プライマリ/統合済み
VRAM - 4096 MB - DDR4 1800 MHz
ドライバー バージョン - 22.10.17.01-220517a-379487E-AMD-Software-Adrenalin-Edition
AMD Windows ドライバー バージョン - 30.0.21017.1000
Direct3D API バージョン - 12.1
Vulkan™ API Version - 1.3.212
OpenCL™ API Version - 2.0
OpenGL® API Version - 4.6
Direct3D® Driver Version - 9.14.10.01521
Vulkan™ Driver Version - 2.0.226
OpenCL® Driver Version - 10.0.3417.0
OpenGL® Driver Version - 29.20.11000.14800
2D ドライバー バージョン - 8.1.1.1634
UI バージョン - 2022.0517.0143.1929
AMD オーディオ ドライバーのバージョン - 10.0.1.23
Driver Provider - Advanced Micro Devices, Inc.
Windows Edition - Windows 10 Professional (64 bit)
Windows バージョン - 21H2

**Comment by f11894** [comment]
https://github.com/nihui/waifu2x-ncnn-vulkan/issues/178

**Comment by f11894** [comment]
詳細なレポートありがとうございます
対処療法ですがドライバのバージョンをAMD Adrenalin 22.5.1に落とせば動作するようです
waifu2x-ncnn-vulkanのバグだった場合nihui氏が対応しないと私には何も出来ないです

**Comment by apapanda** [comment]
情報ありがとうございます。

**Comment by f11894** [comment]
ドライバのバージョン22.6.1で直ったようなので閉じます
