### ISSUE TITLE
UIlang.zh-TW.xaml

### ISSUE THREAD

**Issue by xperiazu21** [f11894/waifu2x-ncnn-vulkan-GUI#3]
I translated the zh-TW language, but I don’t know where to upload it, so I have to upload it here.

[UIlang.zh-TW.zip](https://github.com/f11894/waifu2x-ncnn-vulkan-GUI/files/4397175/UIlang.zh-TW.zip)

**Comment by f11894** [comment]
Thank you for your help with the translation.
