### ISSUE TITLE
Green error image results

### ISSUE THREAD

**Issue by fizhsmile** [f11894/waifu2x-ncnn-vulkan-GUI#4]
Hello. I have some problem with the latest version, results are always error
Color image turned blue
https://imgur.com/a/eJhLLbs
Grayscale image turned green
https://imgur.com/a/HBrPrdW
GPU RX 580 with latest driver

**Comment by f11894** [comment]
It's not a issue with my software, it's a issue with waifu2x-ncnn-vulkan.
https://github.com/nihui/waifu2x-ncnn-vulkan/issues/59

**Comment by f11894** [comment]
This issue was fixed in v2.0.4.
https://github.com/f11894/waifu2x-ncnn-vulkan-GUI/releases/tag/v2.0.4
