### ISSUE TITLE
Contribution: Icon

### ISSUE THREAD

**Issue by flaviojcojr** [f11894/waifu2x-ncnn-vulkan-GUI#7]
I created this icon for the program, using an image into the Public Domain. File is attached. 
Original Image Link: https://commons.wikimedia.org/wiki/File:Anime_Girl_with_cat.svg
I also designate the icon as public domain under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/).
[waifu2x.zip](https://github.com/f11894/waifu2x-ncnn-vulkan-GUI/files/5109229/waifu2x.zip)

**Comment by flaviojcojr** [comment]
> Thank you for your help in creating the icon.
> But this is not what I was expecting.
> I don't want to use anything with a human face on it as an icon.
> 
> アイコン制作に協力いただき感謝します。
> しかしこれは私が期待していたものとは異なります。
> 私は人の顔が描かれたものをアイコンに使いたくありません。
I created others. If you have suggestions, please send!
[icons2.zip](https://github.com/f11894/waifu2x-ncnn-vulkan-GUI/files/5126868/icons2.zip)

**Comment by f11894** [comment]
Thank you for providing a very kawaii icon.
